tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary-fixed": "#ffdea5",
        "on-tertiary": "#ffffff",
        "surface": "#faf9f6",
        "inverse-on-surface": "#f2f1ee",
        "surface-dim": "#dbdad7",
        "surface-container": "#efeeeb",
        "on-error-container": "#93000a",
        "on-secondary-container": "#576846",
        "on-secondary": "#ffffff",
        "on-primary-container": "#806221",
        "inverse-surface": "#2f312f",
        "surface-container-low": "#f4f3f1",
        "on-secondary-fixed": "#111f05",
        "on-surface": "#1a1c1a",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-primary": "#e9c176",
        "surface-bright": "#faf9f6",
        "background": "#faf9f6",
        "on-tertiary-fixed-variant": "#584233",
        "secondary-fixed-dim": "#b9cda4",
        "secondary": "#526442",
        "tertiary-fixed-dim": "#dfc1ac",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#5d4201",
        "on-surface-variant": "#4d453f",
        "primary": "#775a19",
        "on-background": "#1a1c1a",
        "surface-container-high": "#e9e8e5",
        "primary-container": "#ffe2b2",
        "outline-variant": "#d0c4bc",
        "on-tertiary-fixed": "#28180b",
        "tertiary-container": "#ffe0cc",
        "tertiary": "#715a49",
        "on-tertiary-container": "#7a6251",
        "on-secondary-fixed-variant": "#3b4c2c",
        "on-primary": "#ffffff",
        "surface-tint": "#775a19",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#e9c176",
        "surface-container-highest": "#e3e2e0",
        "outline": "#7f756e",
        "secondary-fixed": "#d5e9bf",
        "surface-variant": "#e3e2e0",
        "secondary-container": "#d2e6bc",
        "on-primary-fixed": "#261900",
        "tertiary-fixed": "#fddcc7"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "headline": ["Noto Serif", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
}
