tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "secondary-fixed": "#26fedc",
              "secondary-container": "#006b5b",
              "tertiary": "#ff62c5",
              "on-tertiary-container": "#000000",
              "tertiary-container": "#ff00bd",
              "primary-fixed-dim": "#bc6fff",
              "surface-tint": "#cf96ff",
              "surface-container-high": "#32113d",
              "on-tertiary-fixed": "#350025",
              "secondary": "#26fedc",
              "on-background": "#fbdbff",
              "on-primary-fixed-variant": "#450074",
              "error": "#ff6e84",
              "on-tertiary-fixed-variant": "#710052",
              "secondary-fixed-dim": "#00efce",
              "background": "#1b0424",
              "secondary-dim": "#00efce",
              "on-primary-container": "#37005f",
              "on-secondary": "#005d4f",
              "on-error-container": "#ffb2b9",
              "on-secondary-container": "#ddfff5",
              "on-secondary-fixed": "#00483d",
              "surface-container-low": "#22062c",
              "primary-dim": "#a533ff",
              "surface-container": "#2a0b35",
              "surface": "#1b0424",
              "inverse-on-surface": "#684a70",
              "surface-variant": "#3a1646",
              "outline": "#8a6a92",
              "surface-container-highest": "#3a1646",
              "tertiary-fixed": "#ff89cd",
              "error-dim": "#d73357",
              "on-primary-fixed": "#000000",
              "on-primary": "#480079",
              "on-secondary-fixed-variant": "#006859",
              "on-error": "#490013",
              "primary-container": "#c683ff",
              "outline-variant": "#5a3d62",
              "tertiary-fixed-dim": "#ff6ec7",
              "primary": "#cf96ff",
              "on-surface-variant": "#c39fca",
              "on-surface": "#fbdbff",
              "tertiary-dim": "#ff62c5",
              "surface-bright": "#421b4f",
              "inverse-primary": "#8d00e6",
              "error-container": "#a70138",
              "surface-container-lowest": "#000000",
              "inverse-surface": "#fff7fb",
              "on-tertiary": "#440030",
              "primary-fixed": "#c683ff",
              "surface-dim": "#1b0424"
      },
      "borderRadius": {
              "DEFAULT": "1rem",
              "lg": "2rem",
              "xl": "3rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Epilogue", "sans-serif"],
              "body": ["Be Vietnam Pro", "sans-serif"],
              "label": ["Be Vietnam Pro", "sans-serif"]
      }
    },
  },
}
