tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary": "#ffffff",
        "outline-variant": "#bbb9b3",
        "surface-container": "#f6f3eb",
        "surface-container-high": "#f0eee5",
        "background": "#fffcf5",
        "on-tertiary": "#ffffff",
        "secondary-dim": "#b40026",
        "on-error-container": "#520c00",
        "surface-bright": "#fffcf5",
        "primary-dim": "#745200",
        "primary-container": "#feb700",
        "inverse-surface": "#0e0e0b",
        "secondary-fixed-dim": "#ffafad",
        "on-background": "#383833",
        "secondary-fixed": "#ffc3c1",
        "tertiary-fixed-dim": "#ef8a26",
        "error": "#be2d06",
        "inverse-primary": "#feb700",
        "secondary": "#ca002c",
        "inverse-on-surface": "#9e9d97",
        "tertiary-container": "#ff9735",
        "surface-variant": "#eae8df",
        "tertiary-fixed": "#ff9735",
        "surface-container-highest": "#eae8df",
        "primary-fixed-dim": "#ecaa00",
        "surface-dim": "#e5e3d9",
        "on-primary-fixed-variant": "#5f4200",
        "tertiary-dim": "#884800",
        "error-container": "#f95630",
        "on-tertiary-container": "#4d2600",
        "secondary-container": "#ffc3c1",
        "on-surface-variant": "#65645f",
        "on-secondary-fixed": "#6f0013",
        "on-tertiary-fixed": "#291200",
        "outline": "#82817b",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-container": "#533a00",
        "on-surface": "#383833",
        "surface-tint": "#845d00",
        "on-tertiary-fixed-variant": "#5a2e00",
        "surface-container-low": "#fcf9f2",
        "on-primary-fixed": "#392700",
        "surface": "#fffcf5",
        "primary": "#845d00",
        "error-dim": "#b92902",
        "primary-fixed": "#feb700",
        "tertiary": "#995200",
        "on-secondary-container": "#94001d",
        "on-secondary-fixed-variant": "#a50022"
      },
      "borderRadius": {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Be Vietnam Pro"],
        "label": ["Plus Jakarta Sans"]
      }
    },
  },
}
