tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "inverse-surface": "#2f312e",
              "surface-container-highest": "#e3e2df",
              "primary-fixed": "#d8e8cb",
              "error": "#ba1a1a",
              "on-primary-fixed": "#121f0d",
              "outline": "#757870",
              "on-error-container": "#93000a",
              "tertiary": "#705460",
              "on-tertiary-fixed-variant": "#5a3f4b",
              "on-surface-variant": "#444841",
              "surface-bright": "#faf9f5",
              "primary-fixed-dim": "#bccbb0",
              "surface-variant": "#e3e2df",
              "primary-container": "#6a7961",
              "secondary-fixed": "#f2e1b8",
              "secondary-fixed-dim": "#d5c59e",
              "inverse-primary": "#bccbb0",
              "primary": "#526049",
              "on-secondary-fixed-variant": "#514628",
              "inverse-on-surface": "#f2f1ed",
              "surface-dim": "#dbdad6",
              "on-tertiary-fixed": "#2a151f",
              "on-tertiary-container": "#fffbff",
              "surface-container": "#efeeea",
              "secondary-container": "#f2e1b8",
              "on-secondary": "#ffffff",
              "on-secondary-container": "#706343",
              "surface-container-lowest": "#ffffff",
              "on-error": "#ffffff",
              "on-secondary-fixed": "#231b03",
              "surface-tint": "#54634c",
              "on-primary-fixed-variant": "#3d4b35",
              "on-primary": "#ffffff",
              "surface": "#faf9f5",
              "on-surface": "#1b1c1a",
              "on-background": "#1b1c1a",
              "secondary": "#695d3d",
              "tertiary-container": "#8b6c79",
              "on-primary-container": "#f8ffee",
              "surface-container-high": "#e9e8e4",
              "background": "#faf9f5",
              "tertiary-fixed-dim": "#e1bdcb",
              "outline-variant": "#c5c8be",
              "error-container": "#ffdad6",
              "tertiary-fixed": "#ffd8e7",
              "surface-container-low": "#f4f4f0",
              "on-tertiary": "#ffffff"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "fontFamily": {
              "headline": ["Noto Serif"],
              "body": ["Manrope"],
              "label": ["Manrope"]
      }
    },
  },
}
