tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "tertiary-container": "#2d1e00",
                "on-primary-fixed": "#041a3f",
                "on-secondary-fixed": "#261900",
                "on-tertiary": "#ffffff",
                "surface-container-low": "#f1f3ff",
                "secondary": "#775a19",
                "on-surface": "#041a3f",
                "on-tertiary-fixed": "#261900",
                "error": "#ba1a1a",
                "error-container": "#ffdad6",
                "surface": "#faf9ff",
                "surface-bright": "#faf9ff",
                "surface-variant": "#d9e2ff",
                "on-primary-fixed-variant": "#34466d",
                "outline-variant": "#c5c6cf",
                "on-primary": "#ffffff",
                "on-error-container": "#93000a",
                "primary-container": "#0a1f44",
                "background": "#faf9ff",
                "on-surface-variant": "#44464e",
                "primary-fixed": "#d9e2ff",
                "inverse-on-surface": "#edf0ff",
                "secondary-fixed": "#ffdea5",
                "inverse-surface": "#1d2f55",
                "surface-container": "#e9edff",
                "tertiary-fixed": "#ffdea5",
                "outline": "#75777f",
                "surface-container-high": "#e1e8ff",
                "on-primary-container": "#7687b2",
                "primary": "#00081e",
                "on-tertiary-container": "#a5833f",
                "surface-container-lowest": "#ffffff",
                "tertiary": "#0f0800",
                "primary-fixed-dim": "#b4c6f4",
                "secondary-container": "#fed488",
                "surface-tint": "#4c5e86",
                "on-background": "#041a3f",
                "surface-dim": "#ccdaff",
                "on-secondary-fixed-variant": "#5d4201",
                "on-tertiary-fixed-variant": "#5d4201",
                "on-secondary": "#ffffff",
                "tertiary-fixed-dim": "#e9c176",
                "surface-container-highest": "#d9e2ff",
                "on-secondary-container": "#785a1a",
                "inverse-primary": "#b4c6f4",
                "secondary-fixed-dim": "#e9c176",
                "on-error": "#ffffff"
            },
            "borderRadius": {
                "DEFAULT": "0rem",
                "lg": "0rem",
                "xl": "0rem",
                "full": "9999px"
            },
            "fontFamily": {
                "headline": ["Noto Serif"],
                "body": ["Inter"],
                "label": ["Inter"]
            }
        },
    },
}
