tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-primary-fixed-variant": "#793106",
                "on-background": "#1d1c16",
                "tertiary-fixed-dim": "#b9ccb3",
                "on-primary-container": "#fffbff",
                "tertiary": "#4f604c",
                "on-primary": "#ffffff",
                "surface-container-high": "#ece8df",
                "secondary-container": "#d1eac8",
                "background": "#fef9f0",
                "primary": "#94451a",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed": "#351000",
                "surface": "#fef9f0",
                "inverse-on-surface": "#f5f0e7",
                "secondary": "#4e644a",
                "inverse-primary": "#ffb694",
                "surface-bright": "#fef9f0",
                "on-error-container": "#93000a",
                "error": "#ba1a1a",
                "error-container": "#ffdad6",
                "inverse-surface": "#32302a",
                "outline": "#88736a",
                "outline-variant": "#dbc1b7",
                "surface-container-low": "#f8f3ea",
                "tertiary-container": "#687964",
                "on-surface": "#1d1c16",
                "on-tertiary-container": "#f7fff1",
                "primary-fixed": "#ffdbcc",
                "on-secondary-fixed": "#0c200b",
                "on-secondary": "#ffffff",
                "surface-dim": "#ded9d1",
                "on-tertiary-fixed-variant": "#3b4b38",
                "secondary-fixed": "#d1eac8",
                "primary-container": "#b35c30",
                "primary-fixed-dim": "#ffb694",
                "on-secondary-fixed-variant": "#374c34",
                "on-tertiary-fixed": "#101f0f",
                "surface-variant": "#e7e2d9",
                "surface-tint": "#98471d",
                "tertiary-fixed": "#d5e8ce",
                "surface-container": "#f2ede4",
                "on-error": "#ffffff",
                "on-secondary-container": "#546a4f",
                "on-surface-variant": "#55433b",
                "secondary-fixed-dim": "#b5cdad",
                "surface-container-highest": "#e7e2d9",
                "on-tertiary": "#ffffff"
            },
            "borderRadius": {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
            "fontFamily": {
                "headline": ["Noto Serif"],
                "body": ["Plus Jakarta Sans"],
                "label": ["Be Vietnam Pro"],
                "handwritten": ["Caveat"]
            }
        },
    },
}
