tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-error-container": "#93000a",
              "surface-bright": "#faf9f7",
              "on-surface": "#1a1c1b",
              "error": "#ba1a1a",
              "secondary-container": "#fed488",
              "on-tertiary": "#ffffff",
              "on-secondary": "#ffffff",
              "surface-container-high": "#e9e8e6",
              "surface-dim": "#dadad8",
              "on-secondary-fixed": "#261900",
              "secondary-fixed-dim": "#e9c176",
              "outline-variant": "#d1c5b4",
              "background": "#faf9f7",
              "inverse-primary": "#c8c6c5",
              "surface-container-lowest": "#ffffff",
              "inverse-on-surface": "#f1f1ef",
              "secondary": "#775a19",
              "tertiary-fixed": "#e4e4cc",
              "on-surface-variant": "#4e4639",
              "inverse-surface": "#2f3130",
              "tertiary-fixed-dim": "#c8c8b0",
              "primary-container": "#a7a5a4",
              "on-primary-container": "#3b3b3b",
              "on-background": "#1a1c1b",
              "on-tertiary-fixed": "#1b1d0e",
              "secondary-fixed": "#ffdea5",
              "on-primary": "#ffffff",
              "error-container": "#ffdad6",
              "surface-tint": "#5f5e5e",
              "on-secondary-fixed-variant": "#5d4201",
              "primary": "#5f5e5e",
              "surface-container-low": "#f4f3f1",
              "tertiary": "#5e604d",
              "on-error": "#ffffff",
              "on-primary-fixed-variant": "#474746",
              "on-primary-fixed": "#1c1b1b",
              "surface-variant": "#e3e2e0",
              "primary-fixed": "#e5e2e1",
              "on-secondary-container": "#785a1a",
              "on-tertiary-fixed-variant": "#474836",
              "surface-container-highest": "#e3e2e0",
              "tertiary-container": "#a6a791",
              "surface-container": "#efeeec",
              "primary-fixed-dim": "#c8c6c5",
              "on-tertiary-container": "#3b3c2b",
              "surface": "#faf9f7",
              "outline": "#7f7667"
      },
      "borderRadius": {
              "DEFAULT": "0px",
              "lg": "0px",
              "xl": "0px",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Noto Serif", "serif"],
              "body": ["Manrope", "sans-serif"],
              "label": ["Manrope", "sans-serif"]
      }
    },
  },
}
