tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "secondary-fixed": "#ffc6a0",
              "secondary-fixed-dim": "#ffb37e",
              "primary-container": "#ff7577",
              "primary": "#ba0027",
              "surface-bright": "#f9f6f5",
              "surface-tint": "#ba0027",
              "secondary-dim": "#7f3e00",
              "tertiary-fixed-dim": "#bc8df9",
              "primary-dim": "#a30021",
              "surface-container-high": "#e4e2e1",
              "tertiary-container": "#c89dff",
              "on-secondary-fixed": "#562800",
              "error-container": "#f95630",
              "background": "#f9f6f5",
              "error": "#b02500",
              "on-secondary-fixed-variant": "#803e00",
              "tertiary-dim": "#65379d",
              "on-secondary": "#fff0e8",
              "on-error": "#ffefec",
              "outline-variant": "#afadac",
              "inverse-surface": "#0e0e0e",
              "on-primary": "#ffefee",
              "secondary": "#914700",
              "surface-container-lowest": "#ffffff",
              "inverse-primary": "#ff525b",
              "outline": "#787676",
              "surface-container": "#eae7e7",
              "on-surface": "#2f2f2e",
              "on-primary-fixed-variant": "#60000f",
              "on-background": "#2f2f2e",
              "error-dim": "#b92902",
              "surface-container-low": "#f3f0ef",
              "on-tertiary-fixed-variant": "#4d1c85",
              "inverse-on-surface": "#9e9c9c",
              "on-tertiary-fixed": "#25004b",
              "on-tertiary": "#faefff",
              "on-surface-variant": "#5c5b5b",
              "surface-dim": "#d6d4d3",
              "secondary-container": "#ffc6a0",
              "tertiary": "#7144aa",
              "surface-variant": "#dfdcdc",
              "on-tertiary-container": "#440f7c",
              "surface": "#f9f6f5",
              "on-primary-fixed": "#000000",
              "primary-fixed": "#ff7577",
              "on-secondary-container": "#733700",
              "surface-container-highest": "#dfdcdc",
              "primary-fixed-dim": "#ff5960",
              "on-error-container": "#520c00",
              "on-primary-container": "#4e000a",
              "tertiary-fixed": "#c89dff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Epilogue"],
              "body": ["Be Vietnam Pro"],
              "label": ["Be Vietnam Pro"]
      }
    },
  },
}
