tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-bright": "#2c2c2c",
        "on-surface": "#ffffff",
        "tertiary-dim": "#ff51fa",
        "inverse-on-surface": "#565554",
        "inverse-primary": "#9a00cf",
        "on-surface-variant": "#adaaaa",
        "surface-container-highest": "#262626",
        "on-background": "#ffffff",
        "error-dim": "#d73357",
        "surface-tint": "#e08dff",
        "on-error": "#490013",
        "tertiary-fixed-dim": "#ff61f8",
        "secondary-dim": "#e6c047",
        "inverse-surface": "#fcf8f8",
        "primary-fixed-dim": "#d160ff",
        "surface-container": "#1a1919",
        "on-primary": "#4f006c",
        "secondary": "#f5ce53",
        "on-tertiary-fixed-variant": "#6a006a",
        "error-container": "#a70138",
        "on-primary-container": "#3d0055",
        "tertiary": "#ff51fa",
        "on-tertiary": "#400040",
        "error": "#ff6e84",
        "secondary-fixed": "#f5ce53",
        "on-tertiary-container": "#230023",
        "primary-dim": "#bc00fb",
        "tertiary-fixed": "#ff81f5",
        "surface-variant": "#262626",
        "surface-dim": "#0e0e0e",
        "surface-container-high": "#201f1f",
        "surface": "#0e0e0e",
        "outline": "#777575",
        "on-primary-fixed": "#000000",
        "tertiary-container": "#fe00fe",
        "primary": "#e08dff",
        "surface-container-lowest": "#000000",
        "secondary-fixed-dim": "#e6c047",
        "background": "#0e0e0e",
        "surface-container-low": "#131313",
        "on-tertiary-fixed": "#320032",
        "primary-container": "#d978ff",
        "on-secondary-fixed-variant": "#634e00",
        "on-secondary-container": "#fff7ea",
        "on-error-container": "#ffb2b9"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      }
    },
  },
}
