tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "secondary-fixed-dim": "#bcc7dd",
              "inverse-primary": "#adc7f7",
              "on-secondary-fixed": "#111c2c",
              "on-secondary-fixed-variant": "#3c475a",
              "tertiary-fixed-dim": "#f2bc82",
              "on-surface-variant": "#43474e",
              "on-primary-container": "#86a0cd",
              "background": "#f5faff",
              "primary-fixed": "#d6e3ff",
              "on-primary": "#ffffff",
              "error": "#ba1a1a",
              "inverse-on-surface": "#ecf1f6",
              "surface-container-high": "#e4e9ee",
              "secondary": "#545f72",
              "on-secondary": "#ffffff",
              "on-error-container": "#93000a",
              "surface-container-lowest": "#ffffff",
              "surface-tint": "#455f88",
              "on-surface": "#171c20",
              "surface": "#f5faff",
              "tertiary-fixed": "#ffddba",
              "primary-container": "#1a365d",
              "error-container": "#ffdad6",
              "tertiary": "#321b00",
              "primary": "#002045",
              "outline": "#74777f",
              "surface-bright": "#f5faff",
              "surface-container-low": "#eff4f9",
              "outline-variant": "#c4c6cf",
              "on-primary-fixed": "#001b3c",
              "surface-variant": "#dee3e8",
              "on-tertiary-container": "#c6955e",
              "on-tertiary-fixed-variant": "#633f0f",
              "inverse-surface": "#2c3135",
              "surface-container-highest": "#dee3e8",
              "primary-fixed-dim": "#adc7f7",
              "on-tertiary-fixed": "#2b1700",
              "surface-dim": "#d5dbdf",
              "surface-container": "#e9eef3",
              "on-tertiary": "#ffffff",
              "secondary-fixed": "#d8e3fa",
              "on-background": "#171c20",
              "secondary-container": "#d5e0f7",
              "on-error": "#ffffff",
              "tertiary-container": "#4f2e00",
              "on-secondary-container": "#586377",
              "on-primary-fixed-variant": "#2d476f"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "fontFamily": {
              "headline": ["Manrope", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
      }
    },
  },
}
