tailwind.config = {
    darkMode: "class",
    theme: {
      extend: {
        "colors": {
                "outline-variant": "#d0c5b5",
                "on-primary-fixed-variant": "#5a4312",
                "on-surface-variant": "#4d463a",
                "surface-container-low": "#f6f3ee",
                "secondary-fixed": "#d5eab0",
                "surface-container-lowest": "#ffffff",
                "on-secondary-container": "#56693a",
                "surface": "#fcf9f4",
                "on-surface": "#1c1c19",
                "inverse-surface": "#31302d",
                "on-error-container": "#93000a",
                "inverse-primary": "#e4c285",
                "on-error": "#ffffff",
                "on-tertiary-fixed-variant": "#3b4b3c",
                "on-tertiary-fixed": "#101f13",
                "inverse-on-surface": "#f3f0eb",
                "on-secondary": "#ffffff",
                "surface-variant": "#e5e2dd",
                "secondary-fixed-dim": "#b9ce96",
                "surface-dim": "#dcdad5",
                "on-primary-container": "#543d0c",
                "error": "#ba1a1a",
                "surface-container": "#f0ede9",
                "tertiary": "#526353",
                "on-secondary-fixed": "#121f00",
                "secondary": "#526436",
                "surface-container-high": "#ebe8e3",
                "on-primary-fixed": "#261900",
                "tertiary-fixed": "#d5e7d3",
                "on-background": "#1c1c19",
                "on-secondary-fixed-variant": "#3b4c21",
                "primary": "#745a27",
                "surface-bright": "#fcf9f4",
                "outline": "#7f7668",
                "background": "#fcf9f4",
                "primary-container": "#c9a96e",
                "error-container": "#ffdad6",
                "primary-fixed": "#ffdea4",
                "primary-fixed-dim": "#e4c285",
                "secondary-container": "#d2e8ad",
                "tertiary-container": "#a0b29f",
                "tertiary-fixed-dim": "#b9cbb8",
                "on-primary": "#ffffff",
                "surface-container-highest": "#e5e2dd",
                "on-tertiary-container": "#354536",
                "surface-tint": "#745a27",
                "on-tertiary": "#ffffff"
        },
        "borderRadius": {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
        },
        "fontFamily": {
                "headline": ["Noto Serif"],
                "body": ["Plus Jakarta Sans"],
                "label": ["Plus Jakarta Sans"]
        }
      },
    },
  }
